site_name: modalkit
repo_url: https://github.com/prassanna-ravishankar/modalkit
site_url: https://prassanna-ravishankar.github.io/modalkit
site_description: A library to package, ship and deploy your ML app on Modal
site_author: Prassanna Ravishankar and Ludovic Vannoorenberghe
edit_uri: edit/main/docs/
repo_name: prassanna-ravishankar/modalkit
copyright: Maintained by <a href="https://prassanna-ravishankar.com">prassanna-ravishankar</a>.

nav:
  - Home: index.md
  - User Guide:
    - Getting Started: guide/getting-started.md
    - Configuration: guide/configuration.md
    - Deployment: guide/deployment.md
  - Examples:
    - Basic Usage: examples/basic.md
    - Async Processing: examples/async.md
    - Error Handling: examples/error-handling.md
  - API Reference: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [modalkit]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prassanna-ravishankar/modalkit
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/modalkit

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
